### ISSUE TITLE
If I say no to typescript, the generator bombs. 

### ISSUE THREAD

**Issue by owen2** [nfriend/generator-nf-angular#4]
I'll paste the stack trace later

**Comment by owen2** [comment]
[?] Would you like to use TypeScript? No

C:\Users\Owen\AppData\Roaming\npm\node_modules\generator-nf-angular\node_modules\yeoman-generator\lib\actions\actions.js
:194
    throw new Error('Unable to read "' + filepath + '" file (Error code: ' + e
          ^
Error: Unable to read "C:\Users\Owen\AppData\Roaming\npm\node_modules\generator-nf-angular\app\templates\scripts_contro
llers.js" file (Error code: ENOENT).
    at read (C:\Users\Owen\AppData\Roaming\npm\node_modules\generator-nf-angular\node_modules\yeoman-generator\lib\actio
ns\actions.js:194:11)
    at template (C:\Users\Owen\AppData\Roaming\npm\node_modules\generator-nf-angular\node_modules\yeoman-generator\lib\a
ctions\actions.js:280:19)
    at yeoman.generators.Base.extend.app (C:\Users\Owen\AppData\Roaming\npm\node_modules\generator-nf-angular\app\index.
js:114:18)
    at C:\Users\Owen\AppData\Roaming\npm\node_modules\generator-nf-angular\node_modules\yeoman-generator\lib\base.js:341
:43
    at C:\Users\Owen\AppData\Roaming\npm\node_modules\generator-nf-angular\node_modules\yeoman-generator\node_modules\as
ync\lib\async.js:551:21
    at C:\Users\Owen\AppData\Roaming\npm\node_modules\generator-nf-angular\node_modules\yeoman-generator\node_modules\as
ync\lib\async.js:227:13
    at iterate (C:\Users\Owen\AppData\Roaming\npm\node_modules\generator-nf-angular\node_modules\yeoman-generator\node_m
odules\async\lib\async.js:134:13)
    at C:\Users\Owen\AppData\Roaming\npm\node_modules\generator-nf-angular\node_modules\yeoman-generator\node_modules\as
ync\lib\async.js:145:25
    at C:\Users\Owen\AppData\Roaming\npm\node_modules\generator-nf-angular\node_modules\yeoman-generator\node_modules\as
ync\lib\async.js:229:17
    at C:\Users\Owen\AppData\Roaming\npm\node_modules\generator-nf-angular\node_modules\yeoman-generator\node_modules\as
ync\lib\async.js:556:34

**Comment by nfriend** [comment]
#9bf76a2baf7a6800a1f2805be733e0002d5270c3
